server:
  port: 8080

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/MemberERP
    username: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to CloudSmoothies!

management:
  endpoints:
    web:
      exposure:
        include: "health,info,features"
jwt:
  secret: secret123

---